title: Labs64 Developers ToolBox
description: "Labs64 Developers ToolBox :: Collection of useful tools"

baseurl: /
color-scheme: "#e14817"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
